//! Canonical Balatro item tables, ported from Immolate (lib/items.cl).

// OpenCL source lines 9–71 (J_C_BEGIN..J_C_END), 60 entries
pub const COMMON_JOKERS: &[&str] = &[
    "Joker",
    "Greedy Joker",
    "Lusty Joker",
    "Wrathful Joker",
    "Gluttonous Joker",
    "Jolly Joker",
    "Zany Joker",
    "Mad Joker",
    "Crazy Joker",
    "Droll Joker",
    "Sly Joker",
    "Wily Joker",
    "Clever Joker",
    "Devious Joker",
    "Crafty Joker",
    "Half Joker",
    "Credit Card",
    "Banner",
    "Mystic Summit",
    "8 Ball",
    "Misprint",
    "Raised Fist",
    "Chaos the Clown",
    "Scary Face",
    "Abstract Joker",
    "Delayed Gratification",
    "Gros Michel",
    "Even Steven",
    "Odd Todd",
    "Scholar",
    "Business Card",
    "Supernova",
    "Ride the Bus",
    "Egg",
    "Runner",
    "Ice Cream",
    "Splash",
    "Blue Joker",
    "Faceless Joker",
    "Green Joker",
    "Superposition",
    "To Do List",
    "Cavendish",
    "Red Card",
    "Square Joker",
    "Riff-raff",
    "Photograph",
    "Reserved Parking",
    "Mail-In Rebate",
    "Hallucination",
    "Fortune Teller",
    "Juggler",
    "Drunkard",
    "Golden Joker",
    "Popcorn",
    "Walkie Talkie",
    "Smiley Face",
    "Golden Ticket",
    "Swashbuckler",
    "Hanging Chad",
    "Shoot the Moon",
];

// OpenCL source lines 73–138 (J_U_BEGIN..J_U_END), 64 entries
pub const UNCOMMON_JOKERS: &[&str] = &[
    "Joker Stencil",
    "Four Fingers",
    "Mime",
    "Ceremonial Dagger",
    "Marble Joker",
    "Loyalty Card",
    "Dusk",
    "Fibonacci",
    "Steel Joker",
    "Hack",
    "Pareidolia",
    "Space Joker",
    "Burglar",
    "Blackboard",
    "Sixth Sense",
    "Constellation",
    "Hiker",
    "Card Sharp",
    "Madness",
    "Seance",
    "Shortcut",
    "Hologram",
    "Cloud 9",
    "Rocket",
    "Midas Mask",
    "Luchador",
    "Gift Card",
    "Turtle Bean",
    "Erosion",
    "To the Moon",
    "Stone Joker",
    "Lucky Cat",
    "Bull",
    "Diet Cola",
    "Trading Card",
    "Flash Card",
    "Spare Trousers",
    "Ramen",
    "Seltzer",
    "Castle",
    "Mr. Bones",
    "Acrobat",
    "Sock and Buskin",
    "Troubadour",
    "Certificate",
    "Smeared Joker",
    "Throwback",
    "Rough Gem",
    "Bloodstone",
    "Arrowhead",
    "Onyx Agate",
    "Glass Joker",
    "Showman",
    "Flower Pot",
    "Merry Andy",
    "Oops! All 6s",
    "The Idol",
    "Seeing Double",
    "Matador",
    "Stuntman",
    "Satellite",
    "Cartomancer",
    "Astronomer",
    "Bootstraps",
];

// OpenCL source lines 140–161 (J_R_BEGIN..J_R_END), 20 entries
pub const RARE_JOKERS: &[&str] = &[
    "DNA",
    "Vampire",
    "Vagabond",
    "Baron",
    "Obelisk",
    "Baseball Card",
    "Ancient Joker",
    "Campfire",
    "Blueprint",
    "Wee Joker",
    "Hit the Road",
    "The Duo",
    "The Trio",
    "The Family",
    "The Order",
    "The Tribe",
    "Invisible Joker",
    "Brainstorm",
    "Driver's License",
    "Burnt Joker",
];

// OpenCL source lines 163–169 (J_L_BEGIN..J_L_END), 5 entries
pub const LEGENDARY_JOKERS: &[&str] = &[
    "Canio",
    "Triboulet",
    "Yorick",
    "Chicot",
    "Perkeo",
];

// OpenCL source lines 938–962 (__constant item TAROTS[]), 22 entries
pub const TAROTS: &[&str] = &[
    "The Fool",
    "The Magician",
    "The High Priestess",
    "The Empress",
    "The Emperor",
    "The Hierophant",
    "The Lovers",
    "The Chariot",
    "Justice",
    "The Hermit",
    "The Wheel of Fortune",
    "Strength",
    "The Hanged Man",
    "Death",
    "Temperance",
    "The Devil",
    "The Tower",
    "The Star",
    "The Moon",
    "The Sun",
    "Judgement",
    "The World",
];

// OpenCL source lines 963–977 (__constant item PLANETS[]), 12 entries
pub const PLANETS: &[&str] = &[
    "Mercury",
    "Venus",
    "Earth",
    "Mars",
    "Jupiter",
    "Saturn",
    "Uranus",
    "Neptune",
    "Pluto",
    "Planet X",
    "Ceres",
    "Eris",
];

// OpenCL source lines 1400–1420 (__constant item SPECTRALS[]), 18 entries
// RETRY placeholders represent The Soul and Black Hole (special draw-pool items)
pub const SPECTRALS: &[&str] = &[
    "Familiar",
    "Grim",
    "Incantation",
    "Talisman",
    "Aura",
    "Wraith",
    "Sigil",
    "Ouija",
    "Ectoplasm",
    "Immolate",
    "Ankh",
    "Deja Vu",
    "Hex",
    "Trance",
    "Medium",
    "Cryptid",
    "The Soul",
    "Black Hole",
];

// OpenCL source lines 1364–1398 (__constant item VOUCHERS[], second/full occurrence), 32 entries
pub const VOUCHERS: &[&str] = &[
    "Overstock",
    "Overstock Plus",
    "Clearance Sale",
    "Liquidation",
    "Hone",
    "Glow Up",
    "Reroll Surplus",
    "Reroll Glut",
    "Crystal Ball",
    "Omen Globe",
    "Telescope",
    "Observatory",
    "Grabber",
    "Nacho Tong",
    "Wasteful",
    "Recyclomancy",
    "Tarot Merchant",
    "Tarot Tycoon",
    "Planet Merchant",
    "Planet Tycoon",
    "Seed Money",
    "Money Tree",
    "Blank",
    "Antimatter",
    "Magic Trick",
    "Illusion",
    "Hieroglyph",
    "Petroglyph",
    "Director's Cut",
    "Retcon",
    "Paint Brush",
    "Palette",
];

// OpenCL source lines 1421–1447 (__constant item TAGS[]), 24 entries
pub const TAGS: &[&str] = &[
    "Uncommon Tag",
    "Rare Tag",
    "Negative Tag",
    "Foil Tag",
    "Holographic Tag",
    "Polychrome Tag",
    "Investment Tag",
    "Voucher Tag",
    "Boss Tag",
    "Standard Tag",
    "Charm Tag",
    "Meteor Tag",
    "Buffoon Tag",
    "Handy Tag",
    "Garbage Tag",
    "Ethereal Tag",
    "Coupon Tag",
    "Double Tag",
    "Juggle Tag",
    "D6 Tag",
    "Top-up Tag",
    "Speed Tag",
    "Orbital Tag",
    "Economy Tag",
];

// Finisher bosses (appear on ante % 8 == 0). Source: B_F_BEGIN..B_F_END in items.cl.
pub const BOSSES_FINISHER: &[&str] = &[
    "Amber Acorn",
    "Verdant Leaf",
    "Violet Vessel",
    "Crimson Heart",
    "Cerulean Bell",
];

// Small/Big bosses (appear on ante % 8 != 0). Source: B_BEGIN+2..B_F_BEGIN in items.cl
// (skip Small_Blind + Big_Blind which are the static early-round blinds, not boss picks).
pub const BOSSES_SMALL_BIG: &[&str] = &[
    "The Hook", "The Ox", "The House", "The Wall", "The Wheel", "The Arm",
    "The Club", "The Fish", "The Psychic", "The Goad", "The Water", "The Window",
    "The Manacle", "The Eye", "The Mouth", "The Plant", "The Serpent", "The Pillar",
    "The Needle", "The Head", "The Tooth", "The Flint", "The Mark",
];

// OpenCL source lines 1449–1479 (__constant item BOSSES[]), 28 entries
pub const BOSSES: &[&str] = &[
    "The Arm",
    "The Club",
    "The Eye",
    "Amber Acorn",
    "Cerulean Bell",
    "Crimson Heart",
    "Verdant Leaf",
    "Violet Vessel",
    "The Fish",
    "The Flint",
    "The Goad",
    "The Head",
    "The Hook",
    "The House",
    "The Manacle",
    "The Mark",
    "The Mouth",
    "The Needle",
    "The Ox",
    "The Pillar",
    "The Plant",
    "The Psychic",
    "The Serpent",
    "The Tooth",
    "The Wall",
    "The Water",
    "The Wheel",
    "The Window",
];

// OpenCL source lines 597–607 (__constant item ENHANCEMENTS[]), 8 entries
// (No_Enhancement is the count sentinel, not a real item)
pub const ENHANCEMENTS: &[&str] = &[
    "Bonus Card",
    "Mult Card",
    "Wild Card",
    "Glass Card",
    "Steel Card",
    "Stone Card",
    "Gold Card",
    "Lucky Card",
];

// OpenCL source lines 608–660 (__constant item CARDS[]), 52 entries.
// Rank ordering inside each suit follows Immolate verbatim:
// 2, 3, 4, 5, 6, 7, 8, 9, A, J, K, Q, T.
// Suit ordering: Clubs, Diamonds, Hearts, Spades.
pub const CARDS: &[&str] = &[
    "2 of Clubs", "3 of Clubs", "4 of Clubs", "5 of Clubs", "6 of Clubs",
    "7 of Clubs", "8 of Clubs", "9 of Clubs", "Ace of Clubs", "Jack of Clubs",
    "King of Clubs", "Queen of Clubs", "10 of Clubs",
    "2 of Diamonds", "3 of Diamonds", "4 of Diamonds", "5 of Diamonds",
    "6 of Diamonds", "7 of Diamonds", "8 of Diamonds", "9 of Diamonds",
    "Ace of Diamonds", "Jack of Diamonds", "King of Diamonds",
    "Queen of Diamonds", "10 of Diamonds",
    "2 of Hearts", "3 of Hearts", "4 of Hearts", "5 of Hearts", "6 of Hearts",
    "7 of Hearts", "8 of Hearts", "9 of Hearts", "Ace of Hearts",
    "Jack of Hearts", "King of Hearts", "Queen of Hearts", "10 of Hearts",
    "2 of Spades", "3 of Spades", "4 of Spades", "5 of Spades", "6 of Spades",
    "7 of Spades", "8 of Spades", "9 of Spades", "Ace of Spades",
    "Jack of Spades", "King of Spades", "Queen of Spades", "10 of Spades",
];

// Standard-pack editions (in `standard_edition`'s probability order).
// Foil > 0.92, Holo > 0.96, Poly > 0.988; otherwise base.
pub const STD_EDITIONS: &[&str] = &["No Edition", "Foil", "Holographic", "Polychrome"];

// Standard-pack seals. Threshold tiers (val > 0.75 = Red, > 0.5 = Blue,
// > 0.25 = Gold, else Purple) match Immolate.
pub const SEALS: &[&str] = &["Red Seal", "Blue Seal", "Gold Seal", "Purple Seal"];

// OpenCL source lines 900–917 (__constant weighteditem PACKS[]), 15 entries (item names only)
// First entry {RETRY, 22.42} is the total-weight sentinel, excluded
pub const PACKS: &[&str] = &[
    "Arcana Pack",
    "Jumbo Arcana Pack",
    "Mega Arcana Pack",
    "Celestial Pack",
    "Jumbo Celestial Pack",
    "Mega Celestial Pack",
    "Standard Pack",
    "Jumbo Standard Pack",
    "Mega Standard Pack",
    "Buffoon Pack",
    "Jumbo Buffoon Pack",
    "Mega Buffoon Pack",
    "Spectral Pack",
    "Jumbo Spectral Pack",
    "Mega Spectral Pack",
];
